import { Context, Logger } from 'koishi'
import { DailyReport, AISummaryOutput, InteractionStatistics } from './types'

export class CardRenderer {
  private logger: Logger
  private isRendering: boolean = false
  private renderQueue: Array<() => Promise<void>> = []

  constructor(private ctx: Context) {
    this.logger = ctx.logger('chat-summarizer:card-renderer')
  }

  /**
   * 等待渲染槽位
   */
  private async waitForRenderSlot(): Promise<void> {
    if (!this.isRendering) {
      this.isRendering = true
      return
    }

    this.logger.info('渲染进程繁忙，加入等待队列...')
    return new Promise((resolve) => {
      this.renderQueue.push(async () => {
        this.isRendering = true
        resolve()
      })
    })
  }

  /**
   * 释放渲染槽位
   */
  private releaseRenderSlot(): void {
    this.isRendering = false
    const nextTask = this.renderQueue.shift()
    if (nextTask) {
      this.logger.info('处理队列中的下一个渲染任务')
      nextTask()
    }
  }

  /**
   * 渲染完整的群日报
   */
  async renderDailyReport(report: DailyReport): Promise<Buffer> {
    const startTime = Date.now()

    await this.waitForRenderSlot()
    this.logger.info('开始渲染群日报卡片')

    try {
      const html = this.generateHTML(report)
      const puppeteer = (this.ctx as any).puppeteer

      const imageBuffer = await puppeteer.render(html, async (page, next) => {
        await page.setViewport({
          width: 800,
          height: 1000,
          deviceScaleFactor: 2
        })

        await page.waitForSelector('.daily-report-container')

        // 等待图片加载
        await page.evaluate(() => {
          return new Promise((resolve) => {
            const images = document.querySelectorAll('img')
            let loaded = 0
            const total = images.length

            if (total === 0) {
              resolve(undefined)
              return
            }

            const checkDone = () => {
              loaded++
              if (loaded >= total) resolve(undefined)
            }

            images.forEach((img) => {
              if (img.complete) {
                checkDone()
              } else {
                img.onload = checkDone
                img.onerror = checkDone
              }
            })

            setTimeout(() => resolve(undefined), 5000)
          })
        })

        await new Promise(resolve => setTimeout(resolve, 300))

        const element = await page.$('.daily-report-container')
        if (!element) {
          throw new Error('无法找到报告容器')
        }

        const boundingBox = await element.boundingBox()
        if (!boundingBox) {
          throw new Error('无法获取容器尺寸')
        }

        const screenshot = await page.screenshot({
          type: 'png',
          optimizeForSpeed: false,
          clip: {
            x: Math.max(0, boundingBox.x),
            y: Math.max(0, boundingBox.y),
            width: boundingBox.width,
            height: boundingBox.height
          }
        })

        return screenshot
      })

      const totalTime = Date.now() - startTime
      this.logger.info('群日报渲染成功', { renderTime: totalTime + 'ms' })

      return Buffer.from(imageBuffer, 'base64')
    } catch (error) {
      this.logger.error('群日报渲染失败', error)
      throw error
    } finally {
      this.releaseRenderSlot()
    }
  }

  /**
   * 生成完整的 HTML
   */
  private generateHTML(report: DailyReport): string {
    const styles = this.getStyles()
    const headerCard = this.renderHeaderCard(report)
    const summaryCard = this.renderSummaryCard(report.aiContent)
    const hotTopicsCard = this.renderHotTopicsCard(report.aiContent.hotTopics)
    const importantInfoCard = this.renderImportantInfoCard(report.aiContent.importantInfo)
    const quotesCard = this.renderQuotesCard(report.aiContent.quotes)
    const activityRankingCard = this.renderActivityRankingCard(report.statistics)
    const hourlyDistributionCard = this.renderHourlyDistributionCard(report.statistics)
    const interactionsCard = this.renderInteractionsCard(report.statistics.interactions)

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>${styles}</style>
      </head>
      <body>
        <div class="daily-report-container">
          ${headerCard}
          ${summaryCard}
          ${hotTopicsCard}
          ${importantInfoCard}
          ${quotesCard}
          ${activityRankingCard}
          ${hourlyDistributionCard}
          ${interactionsCard}
          <div class="footer">
            <span>Generated by Chat Summarizer · ${new Date(report.metadata.generatedAt).toLocaleString('zh-CN')}</span>
          </div>
        </div>
      </body>
      </html>
    `

    // 将emoji转换为CDN图片
    return this.convertEmojiToImages(html)
  }

  /**
   * 获取 CSS 样式
   */
  private getStyles(): string {
    return `
      @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;700&display=swap');

      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }

      body {
        font-family: 'Noto Sans SC', 'Noto Color Emoji', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        background: #f5f5f7;
        min-height: 100vh;
      }

      .daily-report-container {
        max-width: 720px;
        margin: 0 auto;
        padding: 40px;
        background: #f5f5f7;
      }

      .card {
        background: #ffffff;
        border-radius: 16px;
        box-shadow: 0 2px 12px rgba(0, 0, 0, 0.06);
        margin-bottom: 16px;
        padding: 20px 24px;
        position: relative;
        overflow: hidden;
        border: 1px solid rgba(0, 0, 0, 0.04);
      }

      .card::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        height: 3px;
        background: linear-gradient(90deg, #1a1a1a, #404040);
      }

      .card-title {
        display: flex;
        align-items: center;
        gap: 8px;
        font-size: 18px;
        font-weight: 700;
        color: #1a1a1a;
        margin-bottom: 16px;
      }

      .card-title .icon {
        font-size: 20px;
      }

      /* 头部卡片 */
      .header-card {
        background: linear-gradient(135deg, #1a1a1a 0%, #333333 100%);
        color: white;
        text-align: center;
        padding: 32px 24px;
      }

      .header-card::before {
        display: none;
      }

      .header-title {
        font-size: 28px;
        font-weight: 700;
        margin-bottom: 8px;
      }

      .header-date {
        font-size: 16px;
        opacity: 0.8;
        margin-bottom: 20px;
      }

      .header-stats {
        display: flex;
        justify-content: center;
        gap: 40px;
      }

      .stat-item {
        text-align: center;
      }

      .stat-value {
        font-size: 32px;
        font-weight: 700;
      }

      .stat-label {
        font-size: 14px;
        opacity: 0.7;
      }

      /* 总结卡片 */
      .summary-overview {
        font-size: 16px;
        line-height: 1.8;
        color: #333;
        margin-bottom: 16px;
        padding: 12px 16px;
        background: #fafafa;
        border-radius: 8px;
        border-left: 4px solid #1a1a1a;
      }

      .summary-highlights {
        margin-bottom: 16px;
      }

      .highlight-item {
        display: flex;
        align-items: flex-start;
        gap: 8px;
        padding: 8px 0;
        color: #444;
        font-size: 15px;
        line-height: 1.6;
      }

      .highlight-bullet {
        color: #1a1a1a;
        font-weight: bold;
      }

      .atmosphere-tag {
        display: inline-block;
        padding: 6px 16px;
        background: #1a1a1a;
        color: white;
        border-radius: 20px;
        font-size: 14px;
        font-weight: 500;
      }

      /* 热点话题卡片 */
      .hot-topic {
        padding: 14px 16px;
        background: #fafafa;
        border-radius: 12px;
        margin-bottom: 12px;
      }

      .hot-topic:last-child {
        margin-bottom: 0;
      }

      .hot-topic-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-bottom: 8px;
      }

      .hot-topic-name {
        font-size: 16px;
        font-weight: 600;
        color: #1a1a1a;
      }

      .heat-tag {
        padding: 2px 10px;
        border-radius: 12px;
        font-size: 12px;
        font-weight: 500;
      }

      .heat-high {
        background: #1a1a1a;
        color: #ffffff;
      }

      .heat-medium {
        background: #e5e5e5;
        color: #333333;
      }

      .heat-low {
        background: #f5f5f5;
        color: #666666;
      }

      .hot-topic-desc {
        font-size: 14px;
        color: #666;
        margin-bottom: 8px;
        line-height: 1.5;
      }

      .hot-topic-participants {
        display: flex;
        flex-wrap: wrap;
        gap: 6px;
      }

      .participant-tag {
        padding: 2px 10px;
        background: #e8e8e8;
        color: #333333;
        border-radius: 12px;
        font-size: 12px;
      }

      /* 重要信息卡片 */
      .important-item {
        display: flex;
        align-items: flex-start;
        gap: 12px;
        padding: 12px 0;
        border-bottom: 1px solid #f0f0f0;
      }

      .important-item:last-child {
        border-bottom: none;
      }

      .info-type-icon {
        width: 32px;
        height: 32px;
        border-radius: 8px;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 16px;
        flex-shrink: 0;
      }

      .type-announcement {
        background: #f0f0f0;
      }

      .type-link {
        background: #e8e8e8;
      }

      .type-resource {
        background: #f5f5f5;
      }

      .type-decision {
        background: #ebebeb;
      }

      .type-other {
        background: #f3f4f6;
      }

      .info-content {
        flex: 1;
        font-size: 14px;
        color: #333;
        line-height: 1.6;
      }

      .info-source {
        font-size: 12px;
        color: #888;
        margin-top: 4px;
      }

      /* 金句卡片 */
      .quote-item {
        padding: 16px;
        background: #fafafa;
        border-radius: 12px;
        margin-bottom: 12px;
        position: relative;
      }

      .quote-item:last-child {
        margin-bottom: 0;
      }

      .quote-mark {
        position: absolute;
        top: 8px;
        left: 12px;
        font-size: 32px;
        color: #1a1a1a;
        opacity: 0.15;
        font-family: Georgia, serif;
      }

      .quote-content {
        font-size: 15px;
        color: #333;
        line-height: 1.7;
        padding-left: 20px;
        font-style: italic;
      }

      .quote-author {
        text-align: right;
        font-size: 13px;
        color: #666;
        margin-top: 8px;
      }

      /* 活跃排行卡片 */
      .ranking-item {
        display: flex;
        align-items: center;
        gap: 12px;
        padding: 10px 0;
        border-bottom: 1px solid #f5f5f5;
      }

      .ranking-item:last-child {
        border-bottom: none;
      }

      .rank-badge {
        width: 28px;
        height: 28px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 14px;
        font-weight: 700;
        flex-shrink: 0;
      }

      .rank-1 {
        background: linear-gradient(135deg, #ffd700, #ffb800);
        color: #704c00;
      }

      .rank-2 {
        background: linear-gradient(135deg, #e0e0e0, #c0c0c0);
        color: #555;
      }

      .rank-3 {
        background: linear-gradient(135deg, #cd7f32, #b87333);
        color: white;
      }

      .rank-other {
        background: #f0f0f0;
        color: #888;
      }

      .ranking-info {
        flex: 1;
        min-width: 0;
      }

      .ranking-username {
        font-size: 15px;
        font-weight: 500;
        color: #333;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }

      .ranking-bar {
        height: 6px;
        background: #e5e7eb;
        border-radius: 3px;
        margin-top: 6px;
        overflow: hidden;
      }

      .ranking-bar-fill {
        height: 100%;
        background: linear-gradient(90deg, #1a1a1a, #404040);
        border-radius: 3px;
        transition: width 0.3s;
      }

      .ranking-count {
        font-size: 14px;
        font-weight: 600;
        color: #1a1a1a;
        flex-shrink: 0;
      }

      /* 时段分布卡片 */
      .hourly-chart {
        display: flex;
        align-items: flex-end;
        justify-content: space-between;
        height: 120px;
        padding: 0 4px;
        margin-bottom: 16px;
      }

      .hour-bar {
        flex: 1;
        margin: 0 2px;
        background: linear-gradient(180deg, #1a1a1a 0%, #404040 100%);
        border-radius: 4px 4px 0 0;
        min-height: 4px;
        position: relative;
      }

      .hour-bar:hover {
        opacity: 0.8;
      }

      .hour-labels {
        display: flex;
        justify-content: space-between;
        padding: 0 4px;
      }

      .hour-label {
        font-size: 10px;
        color: #888;
        text-align: center;
        width: 24px;
      }

      .peak-summary {
        margin-top: 12px;
        padding: 10px 14px;
        background: #fafafa;
        border-radius: 8px;
        font-size: 14px;
        color: #555;
      }

      /* 互动关系卡片 */
      .interaction-section {
        margin-bottom: 16px;
      }

      .interaction-section:last-child {
        margin-bottom: 0;
      }

      .interaction-title {
        font-size: 14px;
        font-weight: 600;
        color: #555;
        margin-bottom: 10px;
      }

      .interaction-item {
        display: flex;
        align-items: center;
        gap: 8px;
        padding: 8px 12px;
        background: #fafafa;
        border-radius: 8px;
        margin-bottom: 6px;
        font-size: 14px;
      }

      .interaction-from {
        color: #1a1a1a;
        font-weight: 500;
      }

      .interaction-arrow {
        color: #ccc;
      }

      .interaction-to {
        color: #333333;
        font-weight: 500;
      }

      .interaction-count {
        margin-left: auto;
        background: #e8e8e8;
        color: #333333;
        padding: 2px 8px;
        border-radius: 10px;
        font-size: 12px;
        font-weight: 500;
      }

      /* 空状态 */
      .empty-state {
        text-align: center;
        padding: 20px;
        color: #888;
        font-size: 14px;
      }

      /* 页脚 */
      .footer {
        text-align: center;
        padding: 16px;
        color: #999999;
        font-size: 12px;
      }

      /* 隐藏空卡片 */
      .card.hidden {
        display: none;
      }

      /* Emoji图片样式 */
      .emoji {
        display: inline-block;
        width: 1.2em;
        height: 1.2em;
        vertical-align: -0.15em;
        margin: 0 0.05em;
        object-fit: contain;
      }

      .card-title .emoji {
        width: 1.1em;
        height: 1.1em;
      }

      .header-title .emoji {
        width: 1em;
        height: 1em;
      }
    `
  }

  /**
   * 渲染头部卡片
   */
  private renderHeaderCard(report: DailyReport): string {
    const stats = report.statistics.basicStats
    const guildInfo = report.guildId === 'private' ? '私聊记录' : `群 ${report.guildId}`

    return `
      <div class="card header-card">
        <div class="header-title">📰 群日报</div>
        <div class="header-date">${report.date} · ${guildInfo}</div>
        <div class="header-stats">
          <div class="stat-item">
            <div class="stat-value">${stats.totalMessages}</div>
            <div class="stat-label">消息总数</div>
          </div>
          <div class="stat-item">
            <div class="stat-value">${stats.uniqueUsers}</div>
            <div class="stat-label">参与人数</div>
          </div>
          <div class="stat-item">
            <div class="stat-value">${stats.avgMessagesPerUser}</div>
            <div class="stat-label">人均发言</div>
          </div>
        </div>
      </div>
    `
  }

  /**
   * 渲染总结卡片
   */
  private renderSummaryCard(aiContent: AISummaryOutput): string {
    const highlightsHtml = aiContent.summary.highlights
      .map(h => `<div class="highlight-item"><span class="highlight-bullet">•</span><span>${this.escapeHtml(h)}</span></div>`)
      .join('')

    return `
      <div class="card">
        <div class="card-title"><span class="icon">📝</span>今日总结</div>
        <div class="summary-overview">${this.escapeHtml(aiContent.summary.overview)}</div>
        <div class="summary-highlights">${highlightsHtml}</div>
        <div class="atmosphere-tag">🎭 ${this.escapeHtml(aiContent.summary.atmosphere)}</div>
      </div>
    `
  }

  /**
   * 渲染热点话题卡片
   */
  private renderHotTopicsCard(hotTopics: AISummaryOutput['hotTopics']): string {
    if (!hotTopics || hotTopics.length === 0) {
      return ''
    }

    const topicsHtml = hotTopics.map(topic => {
      const heatClass = `heat-${topic.heatLevel}`
      const heatText = topic.heatLevel === 'high' ? '🔥 热门' :
                       topic.heatLevel === 'medium' ? '⭐ 活跃' : '💬 一般'
      const participantsHtml = topic.participants
        .slice(0, 5)
        .map(p => `<span class="participant-tag">${this.escapeHtml(p)}</span>`)
        .join('')

      return `
        <div class="hot-topic">
          <div class="hot-topic-header">
            <span class="hot-topic-name">${this.escapeHtml(topic.topic)}</span>
            <span class="heat-tag ${heatClass}">${heatText}</span>
          </div>
          <div class="hot-topic-desc">${this.escapeHtml(topic.description)}</div>
          <div class="hot-topic-participants">${participantsHtml}</div>
        </div>
      `
    }).join('')

    return `
      <div class="card">
        <div class="card-title"><span class="icon">🔥</span>热点话题</div>
        ${topicsHtml}
      </div>
    `
  }

  /**
   * 渲染重要信息卡片
   */
  private renderImportantInfoCard(importantInfo: AISummaryOutput['importantInfo']): string {
    if (!importantInfo || importantInfo.length === 0) {
      return ''
    }

    const typeIcons: Record<string, { icon: string; class: string }> = {
      announcement: { icon: '📢', class: 'type-announcement' },
      link: { icon: '🔗', class: 'type-link' },
      resource: { icon: '📦', class: 'type-resource' },
      decision: { icon: '✅', class: 'type-decision' },
      other: { icon: '📌', class: 'type-other' }
    }

    const itemsHtml = importantInfo.map(info => {
      const typeInfo = typeIcons[info.type] || typeIcons.other
      const sourceHtml = info.source ? `<div class="info-source">—— ${this.escapeHtml(info.source)}</div>` : ''
      // 清理内容中的 URL 和图片链接
      const cleanedContent = this.cleanUrlsAndImages(info.content)
      // 如果清理后内容为空，跳过这条
      if (!cleanedContent) return ''

      return `
        <div class="important-item">
          <div class="info-type-icon ${typeInfo.class}">${typeInfo.icon}</div>
          <div class="info-content">
            ${this.escapeHtml(cleanedContent)}
            ${sourceHtml}
          </div>
        </div>
      `
    }).filter(html => html).join('')

    // 如果所有条目都被过滤掉了，不显示卡片
    if (!itemsHtml) {
      return ''
    }

    return `
      <div class="card">
        <div class="card-title"><span class="icon">📌</span>重要信息</div>
        ${itemsHtml}
      </div>
    `
  }

  /**
   * 渲染金句卡片
   */
  private renderQuotesCard(quotes: AISummaryOutput['quotes']): string {
    if (!quotes || quotes.length === 0) {
      return ''
    }

    const quotesHtml = quotes.map(quote => `
      <div class="quote-item">
        <span class="quote-mark">"</span>
        <div class="quote-content">${this.escapeHtml(quote.content)}</div>
        <div class="quote-author">—— ${this.escapeHtml(quote.author)}</div>
      </div>
    `).join('')

    return `
      <div class="card">
        <div class="card-title"><span class="icon">💬</span>金句精选</div>
        ${quotesHtml}
      </div>
    `
  }

  /**
   * 渲染活跃排行卡片
   */
  private renderActivityRankingCard(statistics: InteractionStatistics): string {
    const ranking = statistics.activityRanking
    if (!ranking || ranking.length === 0) {
      return ''
    }

    const maxCount = ranking[0]?.messageCount || 1

    const rankingsHtml = ranking.slice(0, 10).map(item => {
      const percentage = Math.round((item.messageCount / maxCount) * 100)
      let rankClass = 'rank-other'
      let rankIcon = item.rank.toString()

      if (item.rank === 1) {
        rankClass = 'rank-1'
        rankIcon = '🥇'
      } else if (item.rank === 2) {
        rankClass = 'rank-2'
        rankIcon = '🥈'
      } else if (item.rank === 3) {
        rankClass = 'rank-3'
        rankIcon = '🥉'
      }

      return `
        <div class="ranking-item">
          <div class="rank-badge ${rankClass}">${rankIcon}</div>
          <div class="ranking-info">
            <div class="ranking-username">${this.escapeHtml(item.username)}</div>
            <div class="ranking-bar">
              <div class="ranking-bar-fill" style="width: ${percentage}%"></div>
            </div>
          </div>
          <div class="ranking-count">${item.messageCount} 条</div>
        </div>
      `
    }).join('')

    return `
      <div class="card">
        <div class="card-title"><span class="icon">👑</span>活跃排行</div>
        ${rankingsHtml}
      </div>
    `
  }

  /**
   * 渲染时段分布卡片
   */
  private renderHourlyDistributionCard(statistics: InteractionStatistics): string {
    const distribution = statistics.hourlyDistribution
    if (!distribution || distribution.length === 0) {
      return ''
    }

    const maxCount = Math.max(...distribution.map(d => d.count), 1)

    const barsHtml = distribution.map(item => {
      const height = Math.max((item.count / maxCount) * 100, 4)
      return `<div class="hour-bar" style="height: ${height}%" title="${item.hour}:00 - ${item.count}条"></div>`
    }).join('')

    const labelsHtml = [0, 6, 12, 18, 23].map(h =>
      `<span class="hour-label">${h}</span>`
    ).join('')

    const peakHour = statistics.basicStats.peakHour
    const peakCount = distribution[peakHour]?.count || 0
    const period = this.getPeriodDescription(peakHour)

    return `
      <div class="card">
        <div class="card-title"><span class="icon">📈</span>时段分布</div>
        <div class="hourly-chart">${barsHtml}</div>
        <div class="hour-labels">${labelsHtml}</div>
        <div class="peak-summary">
          📍 高峰时段：${period} ${peakHour}:00 (${peakCount} 条消息)
        </div>
      </div>
    `
  }

  /**
   * 渲染互动关系卡片
   */
  private renderInteractionsCard(interactions: InteractionStatistics['interactions']): string {
    const hasMentions = interactions.mentions && interactions.mentions.length > 0
    const hasReplies = interactions.replies && interactions.replies.length > 0

    if (!hasMentions && !hasReplies) {
      return ''
    }

    let contentHtml = ''

    if (hasMentions) {
      const mentionsHtml = interactions.mentions.slice(0, 5).map(item => `
        <div class="interaction-item">
          <span class="interaction-from">${this.escapeHtml(item.from)}</span>
          <span class="interaction-arrow">→</span>
          <span class="interaction-to">@${this.escapeHtml(item.to)}</span>
          <span class="interaction-count">${item.count} 次</span>
        </div>
      `).join('')

      contentHtml += `
        <div class="interaction-section">
          <div class="interaction-title">📣 @提及排行</div>
          ${mentionsHtml}
        </div>
      `
    }

    if (hasReplies) {
      const repliesHtml = interactions.replies.slice(0, 5).map(item => `
        <div class="interaction-item">
          <span class="interaction-from">${this.escapeHtml(item.from)}</span>
          <span class="interaction-arrow">↩</span>
          <span class="interaction-to">${this.escapeHtml(item.to)}</span>
          <span class="interaction-count">${item.count} 次</span>
        </div>
      `).join('')

      contentHtml += `
        <div class="interaction-section">
          <div class="interaction-title">💬 回复排行</div>
          ${repliesHtml}
        </div>
      `
    }

    return `
      <div class="card">
        <div class="card-title"><span class="icon">🤝</span>互动关系</div>
        ${contentHtml}
      </div>
    `
  }

  /**
   * 获取时段描述
   */
  private getPeriodDescription(hour: number): string {
    if (hour >= 6 && hour < 12) return '上午'
    if (hour >= 12 && hour < 14) return '中午'
    if (hour >= 14 && hour < 18) return '下午'
    if (hour >= 18 && hour < 22) return '晚上'
    return '深夜'
  }

  /**
   * HTML 转义
   */
  private escapeHtml(text: string): string {
    if (!text) return ''
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;')
  }

  /**
   * 将文本中的emoji转换为图片标签
   */
  private convertEmojiToImages(html: string): string {
    const emojiBaseUrl = 'https://cdn.bootcdn.net/ajax/libs/twemoji/16.0.1/72x72/'

    const emojiRegex = /(?:[\u2600-\u26FF\u2700-\u27BF]|(?:\uD83C[\uDF00-\uDFFF])|(?:\uD83D[\uDC00-\uDE4F])|(?:\uD83D[\uDE80-\uDEFF])|(?:\uD83E[\uDD00-\uDDFF])|(?:\uD83E[\uDE00-\uDEFF])|(?:\uD83C[\uDDE6-\uDDFF])|(?:\uD83C[\uDDF0-\uDDFF])|[\u23E9-\u23F3\u23F8-\u23FA\u2600-\u2604\u260E\u2611\u2614-\u2615\u2618\u261D\u2620\u2622-\u2623\u2626\u262A\u262E-\u262F\u2638-\u263A\u2640\u2642\u2648-\u2653\u2660\u2663\u2665-\u2666\u2668\u267B\u267F\u2692-\u2697\u2699\u269B-\u269C\u26A0-\u26A1\u26AA-\u26AB\u26B0-\u26B1\u26BD-\u26BE\u26C4-\u26C5\u26C8\u26CE-\u26CF\u26D1\u26D3-\u26D4\u26E9-\u26EA\u26F0-\u26F5\u26F7-\u26FA\u26FD\u2702\u2705\u2708-\u270D\u270F\u2712\u2714\u2716\u271D\u2721\u2728\u2733-\u2734\u2744\u2747\u274C\u274E\u2753-\u2755\u2757\u2763-\u2764\u2795-\u2797\u27A1\u27B0\u27BF\u2934-\u2935\u2B05-\u2B07\u2B1B-\u2B1C\u2B50\u2B55\u3030\u303D\u3297\u3299]|(?:\uD83C\uDFF4\uDB40\uDC67\uDB40\uDC62(?:\uDB40\uDC77\uDB40\uDC6C\uDB40\uDC73|\uDB40\uDC73\uDB40\uDC63\uDB40\uDC74|\uDB40\uDC65\uDB40\uDC6E\uDB40\uDC67)\uDB40\uDC7F))/g

    const result = html.replace(emojiRegex, (match) => {
      try {
        const codePoint = this.getEmojiCodePoint(match)
        if (codePoint) {
          const escapedMatch = match.replace(/["'<>&]/g, (char) => {
            switch (char) {
              case '"': return '&quot;'
              case "'": return '&#39;'
              case '<': return '&lt;'
              case '>': return '&gt;'
              case '&': return '&amp;'
              default: return char
            }
          })
          return `<img class="emoji" src="${emojiBaseUrl}${codePoint}.png" alt="${escapedMatch}" loading="eager" onerror="this.style.display='none'">`
        }
        return match
      } catch {
        return match
      }
    })

    return result
  }

  /**
   * 获取emoji的Unicode码点
   */
  private getEmojiCodePoint(emoji: string): string | null {
    try {
      const codePoints = []
      let i = 0

      while (i < emoji.length) {
        const code = emoji.codePointAt(i)
        if (code) {
          if (code !== 0xFE0F && code !== 0x200D) {
            codePoints.push(code.toString(16))
          }
          if (code > 0xFFFF) {
            i += 2
          } else {
            i += 1
          }
        } else {
          i += 1
        }
      }

      let result = codePoints.join('-')

      if (result.includes('1f3fb') || result.includes('1f3fc') || result.includes('1f3fd') || result.includes('1f3fe') || result.includes('1f3ff')) {
        result = codePoints[0]
      }

      return result.length > 0 ? result : null
    } catch {
      return null
    }
  }

  /**
   * 清理文本中的 URL 和图片链接
   */
  private cleanUrlsAndImages(text: string): string {
    if (!text) return ''
    return text
      // 移除 [图片] 标记
      .replace(/\[图片\]/g, '')
      // 移除 Markdown 图片语法 ![alt](url)
      .replace(/!\[.*?\]\(.*?\)/g, '')
      // 移除 Markdown 链接语法 [text](url) 但保留 text
      .replace(/\[(.*?)\]\(.*?\)/g, '$1')
      // 移除独立的 URL（http/https）
      .replace(/https?:\/\/[^\s<>"{}|\\^`\[\]]+/gi, '')
      // 移除类似 <image url="..."> 的标签
      .replace(/<image[^>]*>/gi, '')
      // 移除类似 <img src="..."> 的标签
      .replace(/<img[^>]*>/gi, '')
      // 清理多余的空白
      .replace(/\s+/g, ' ')
      .trim()
  }
}
